# Name your workflow
name: "00 - Hello world"

# Define your event(s)
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master

# Define your job(s)
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:

  # Name your job
  job-1:

    # Define your runner(s)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # Define your step(s)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - name: Hello world
        run: echo "Hello world"

      - name: Another step
        run: |
          Write-Output "Hello world from PowerShell"
          Write-Output "This is another line"
          Write-Output ("Is Windows: {0}" -f $IsWindows)
          Write-Output ("Is Linux: {0}" -f $IsLinux)
        shell: pwsh