name: "01a - Using Actions"

on:
  push:
    branches:
      - master

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository # Why is it called "checkout", and not "clone"?!
        uses: actions/checkout@v2.3.3

      - name: List contents
        run: Get-ChildItem
        shell: pwsh