name: "01b - Using Actions"

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3

      - name: Print GITHUB_WORKSPACE
        run: echo ${{ env.GITHUB_WORKSPACE }}

        # https://github.com/marketplace/actions/azure-blob-storage-upload
      - name: Azure Blob Upload
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_BLOB_SAS_CONNECTIONSTRING }}
          container_name: winadmins-githubactions
          source_dir: ${{ env.GITHUB_WORKSPACE }}
          sync: true