name: "02 - Environment variables"
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

on:
  push:
    branches:
      - master

jobs:
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Accessing GITHUB_WORKFLOW (default) environment variable in the shell
        run: Write-Output $env:GITHUB_WORKFLOW
        shell: pwsh

      - name: Create new environment variables to use in later steps
        #run: echo "my_own_variable=yellow" >> $GITHUB_ENV
        run: Write-Output "my_own_variable=yellow" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Read GITHUB_ENV
        run: Write-Output $env:GITHUB_ENV; Get-Content $env:GITHUB_ENV; Test-Path $env:GITHUB_ENV
        shell: pwsh

      - name: Long list GITHUB_ENV
        run: ls -lash $GITHUB_ENV
      
      - name: Read my_own_variable
        run: echo $my_own_variable


        # How to reference an environment variable
        # How to set an environment variable:
          # - a means of sharing data between steps