name: "02 - Multiple jobs"
# show parallelism as well as depends on

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - Name: Print datetime
        run: Get-Date
        shell: pwsh

  job-2:
    runs-on: windows-latest
    steps:
      - Name: Print datetime
        run: Get-Date
        shell: pwsh