name: "02 - Environment variables"
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

on:
  push:
    branches:
      - master

jobs:
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Define and print variable x
        run: |
          $x = "Hello world"
          Write-Output $x
        shell: pwsh

      - name: Print variable x again
        run: Write-Output $x
        shell: pwsh

      - name: Accessing GITHUB_WORKFLOW (default) environment variable in the shell
        run: Write-Output $env:GITHUB_WORKFLOW
        shell: pwsh

      - name: Create new environment variable to use in later steps
        #run: echo "my_own_variable=yellow" >> $GITHUB_ENV
        run: Write-Output "my_own_variable=yellow" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Read my_own_variable
        run: echo $my_own_variable

      - name: Create new multi line environment variable 
        run: |
          echo 'DISTRIBUTIONINFO<<XYZ' >> $GITHUB_ENV
          cat /etc/*lease >> $GITHUB_ENV
          echo 'XYZ' >> $GITHUB_ENV

      - name: Read DISTRIBUTIONINFO
        run: echo $DISTRIBUTIONINFO

        # How to reference an environment variable
        # How to set an environment variable:
          # - a means of sharing data between steps