name: "02 - Environment variables"
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

on:
  push:
    branches:
      - master

jobs:
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Accessing GITHUB_WORKFLOW environment variable in the shell
        run: Write-Output $env:GITHUB_WORKFLOW
        shell: pwsh

      - name: Same again, but using env
        env:
          somevariable: ${{ cat /etc/*lease }}
        run: Write-Output $env:somevariable
        shell: pwsh

        # How to reference an environment variable
        # Multi line run vs single line
        # How to set an environment variable:
          # - a means of sharing data between steps