name: "02 - Multiple jobs"

on:
  push:
    branches:
      - idonotexist

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print datetime
        run: Get-Date
        shell: pwsh

  job-2:
    runs-on: windows-latest
    needs: job-1
    steps:
      - name: Print datetime
        run: Get-Date
        shell: pwsh