name: "03 - If"
# On commit message?
on:
  push:
    branches:
      - idonotexist

jobs:
  main:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Hello world
        run: echo "Hello world"