name: "04 - Multiple jobs"
# show parallelism as well as depends on
# sharing data between jobs? show we can't share environment variables

on:
  push:
    branches:
      - idonotexist

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"