name: "04b - Job again again, working with a job matrix"
# strategy matrix jobs

on:
  push:
    branches:
      - idonotexist

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.05]
    steps:
      - name: Hello world
        run: echo "Hello world"