name: "05 - If, paths and paths-ignore"

on:
  push:
    branches:
      - idonotexist
    #paths-ignore:
    #  - '.github/workflows/*.yml'
    #paths:
    #  - 'adamcook-mycicdtestrepo/Public/*.ps1'

jobs:
  main:
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Hello world
        run: echo "Hello world"