name: "Testing 123"

on: 
  push:
    branches:
      - master

jobs:
  job-1:
    name: Testing123
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Print
        run: |
          echo "${{toJSON(github.event)}}"
