name: "Testing 123"

on: 
  push:
    branches:
      - master

jobs:
  job-1:
    name: Testing123
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Print
        run: |
          $github = ${{toJSON(github.event)}} | ConvertFrom-Json -Depth 10
          Write-Host $github.head_commit.message
        shell: pwsh
