name: "Testing 123"

on: 
  push:
    branches:
      - master

jobs:
  job-1:
    name: Testing123
    runs-on: ubuntu-latest
    services:
      shlink:
        image: shlinkio/shlink
        ports: 
          - 8080:8080
        env:
          IS_HTTPS_ENABLED: false
          GEOLITE_LICENSE_KEY: ${{ secrets.key }}
          DEFAULT_DOMAIN: bullshit.abc
    steps:
      - name: Bastardise DNS
        run: echo "127.0.0.1 bullshit.abc" | sudo tee -a /etc/hosts

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.9

