name: "Environment variables and step outputs"

on: 
  push:
    branches:
      - master

jobs:
  job-1:
    name: Testing123
    runs-on: ubuntu-latest
    services:
      shlink:
        image: shlinkio/shlink:stable
        ports: 
          - 8080:8080
        env:
          IS_HTTPS_ENABLED: false
          GEOLITE_LICENSE_KEY: ${{ secrets.key }}
          DEFAULT_DOMAIN: bullshit.abc
        options: --name shlink
    steps:
      - name: Bastardise DNS
        run: echo "127.0.0.1 bullshit.abc" | sudo tee -a /etc/hosts

      - name: Generate Shlink API key and output to env var file
        run: echo "zing=$(docker exec -t shlink shlink api-key:generate --no-ansi | head -2 | tail -1)" >> $GITHUB_ENV

      - name: Print Shlink API key from env var
        run: echo "${{ env.zing }}"

      - name: Generate Shlink API key and output as step output
        id: my_step
        run: echo "::set-output name=zing::$(docker exec -t shlink shlink api-key:generate --no-ansi | head -2 | tail -1)"

      - name: Print Shlink API key from step output
        run: echo "${{ steps.my_step.outputs.zing }}"
