name: "Execute me when a new tag is pushed"

on: 
  push:
    paths-ignore:
      .github/workflows/**
    tags:
      - '*'

jobs:
  job1:
    name: Say hello to the world :-)
    runs-on: ubuntu-18.04
    steps:
    - name: Print 'hello world!'
      run: Write-Host "Hello world!"
      shell: pwsh
