name: "My testing workflow :-)"

on: 
  push:
    paths-ignore:
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'shipit!')"
    steps:
    - name: Set environment variables
      run: |
        $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
        Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
        Write-Output "::set-env name=GH_USERNAME::$Username"
      shell: pwsh
    
    - name: Get environment variables (bash)
      run: echo $GH_PROJECTNAME && echo $GH_USERNAME

    - name: Checkout repository
      uses: actions/checkout@v2.3.1
      with:
        path: folder/${{ env.GH_PROJECTNAME }}

    - name: Create archive of repository
      run: |
        mkdir somedirectory
        cd folder/$GH_PROJECTNAME
        zip -r ${GITHUB_WORKSPACE}/somedirectory/${GH_PROJECTNAME}_1.0.0.zip .

    - name: Create text file
      run: echo "Hello world" >> folder/${GH_PROJECTNAME}/test.txt

    - name: git config
      run: |
        cd folder/$GH_PROJECTNAME
        git config --global user.name "github@cookadam.co.uk"
        git config --global user.name "codaamok"
        git commit -m "Added test.txt" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: folder/${{ env.GH_PROJECTNAME }}
