name: "My testing workflow"

on: 
  push:
    paths-ignore:
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
        Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
        Write-Output "::set-env name=GH_USERNAME::$Username"
      shell: pwsh

    - name: Checkout repository
      uses: actions/checkout@v2.3.1
      with:
        path: folder/${{ env.GH_PROJECTNAME }}

    - name: Create archive of repository
      run: |
        mkdir somedirectory
        cd folder/$GH_PROJECTNAME
        zip -r ${GITHUB_WORKSPACE}/somedirectory/${GH_PROJECTNAME}_1.0.0.zip .
  
  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: List directory recursively
      run: ls -R