name: "Publish new version to PowerShell Gallery when something is pushed to the master branch"

on: 
  push:
    paths-ignore:
      - .github/workflows/**
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install InvokeBuild module
      run: Install-Module InvokeBuild -ErrorAction Stop -Force
      shell: pwsh
    - name: Import InvokeBuild module
      run: Import-Module InvokeBuild -ErrorAction Stop
      shell: pwsh
    - name: Invoke-Build
      run: Invoke-Build -ModuleName "adamcook-mycicdtestrepo"
      shell: pwsh
    - name: Publish module
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      run: Publish-Module -Path .\build\*\ -NuGetApiKey $env:PSGALLERY_API_KEY -ErrorAction Stop -Force
      shell: pwsh
    - name: variable sharing test
      run: $variable1 = "Hello world"
      shell: pwsh
      run: Write-Host ("The value of variable1 is {0}" -f $variable1)
      shell: pwsh
