name: "Publish new version to PowerShell Gallery when something is pushed to the master branch"

on: 
  push:
    paths-ignore:
      - .github/workflows/**
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-18.04
    steps:
    - name: variable sharing test
      run: |
        Write-Output "Hello world"
        Write-Output "Hello again, is it me..."
        Write-Output "You are looking for"
        Write-Output $env:GITHUB_REPOSITORY
      shell: pwsh