name: "Publish new version to PowerShell Gallery when something is pushed to the master branch"

on: 
  push:
    paths-ignore:
      - .github/workflows/**
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-18.04
    steps:
    - name: Step 1
      run: |
        Write-Output "Step 1"
        $Date = Get-Date
        Write-Output $Date
        Write-Output "::set-env name=FOO::$Date"
      shell: pwsh
    - name: Step 2
      run: |
        Write-Output "Step 2"
        Write-Output $Date