name: "Empty CHANGELOG.md and commit to master"

on: 
  push:
    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Job 1
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Print contents of CHNAGELOG.md
      run: Get-Content -Path ".\CHANGELOG.md"
      shell: pwsh