name: "Publish new version to PowerShell Gallery when something is pushed to the master branch"

on: 
  push:
    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh