name: "My testing workflow"

on: 
  push:
    paths-ignore:
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
    - name: Set environment variables
      run: |
        $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
        Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
        Write-Output "::set-env name=GH_USERNAME::$Username"
      shell: pwsh
    
    - name: Get environment variables (bash)
      run: echo $GH_PROJECTNAME && echo $GH_USERNAME
