name: "Publish new version to PowerShell Gallery when something is pushed to the master branch"

on: 
  push:
    paths-ignore:
      - build/**
      - '*.md'

    branches:
      - master

jobs:
  publish-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.1
    - name: Set environment variables
      run: |
        $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
        Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
        Write-Output "::set-env name=GH_USERNAME::$Username"
      shell: pwsh
    - name: Step 1
      run: |
        Write-Output $Pwd.Path
        ls
        Install-Module -Name "ChangelogManagement" -Scope "CurrentUser" -Force -ErrorAction "Stop"
        $ChangeLog = Get-ChangeLogData -Path .\$env:GH_PROJECTNAME\CHANGELOG.md -ErrorAction "Stop"

        $EmptyUnreleasedChangeLog = $true
        $ReleaseNotes = foreach ($Property in $ChangeLog.Unreleased.Data.PSObject.Properties.Name) {
          $Data = $ChangeLog.Unreleased.Data.$Property

          if ($Data) {
            $EmptyUnreleasedChangeLog = $false

            Write-Output $Property

            foreach ($item in $Data) {
              Write-Output ("- {0}" -f $item)
            }
          }
        }

        if ($EmptyUnreleasedChangeLog -eq $true) {
          throw "Can not deploy with empty changelog"
        }

        Write-Output ("::set-env name=changelog::{0}" -f ($ChangeLog | ConvertTo-Json -Depth 3))
        Write-Output ("::set-env name=releasenotes::{0}" -f $ReleaseNotes)
      shell: pwsh
    - name: Step 2
      run: |
        Update-ModuleManifest -Path $env:GH_PROJECTNAME\adamcook-mycicdtestrepo.psd1 -ReleaseNotes $env:releasenotes
      shell: pwsh
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: manifest.psd1
        path: $GH_PROJECTNAME\adamcook-mycicdtestrepo.psd1