name: "Publish"

on: 
  push:
    branches:
      - master

jobs:
  job-main:
    name: main1
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Set environment variables
        run: |
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
          Write-Output "::set-env name=GH_USERNAME::$Username"
        shell: powershell

      - name: Test
        run: |
          Copy-Item -Path .\ -Destination \\sccm\dummy -Recurse -Force 
        shell: powershell
