name: "Publish"

on: 
  push:
    branches:
      - master

jobs:
  job-main:
    name: main
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, ':shipit:')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Set environment variables
        run: |
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          Write-Output "::set-env name=GH_PROJECTNAME::$ProjectName"
          Write-Output "::set-env name=GH_USERNAME::$Username"
        shell: pwsh

      - name: List C drive
        run: |
          Get-ChildItem -Path "C:\"
        shell: pwsh
